# Generated by Django 5.2.7 on 2025-12-13 22:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del departamento o zona', max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del departamento', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('operador', 'Operador')], default='operador', help_text='Rol del usuario en el sistema', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Barrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Barrera Principal', help_text='Nombre de la barrera', max_length=100)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='cerrada', help_text='Estado actual de la barrera', max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(help_text='Departamento donde se encuentra la barrera', on_delete=django.db.models.deletion.CASCADE, related_name='barreras', to='api.departamento')),
            ],
            options={
                'verbose_name': 'Barrera',
                'verbose_name_plural': 'Barreras',
                'db_table': 'barreras',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(help_text='Código único del sensor RFID (UID/MAC)', max_length=50, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del sensor', max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('bloqueado', 'Bloqueado'), ('perdido', 'Perdido')], default='inactivo', help_text='Estado actual del sensor', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(blank=True, help_text='Departamento al que pertenece el sensor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensores', to='api.departamento')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario al que está vinculado el sensor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
                'db_table': 'sensores',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('acceso_sensor', 'Acceso con Sensor'), ('apertura_manual', 'Apertura Manual'), ('cierre_manual', 'Cierre Manual')], help_text='Tipo de evento', max_length=20)),
                ('resultado', models.CharField(choices=[('permitido', 'Permitido'), ('denegado', 'Denegado')], help_text='Resultado del evento', max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales del evento', null=True)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('departamento', models.ForeignKey(help_text='Departamento donde ocurrió el evento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='api.departamento')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que generó el evento (si fue manual)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to=settings.AUTH_USER_MODEL)),
                ('sensor', models.ForeignKey(blank=True, help_text='Sensor que generó el evento (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='api.sensor')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'eventos',
                'ordering': ['-fecha_evento'],
            },
        ),
    ]
